[workspace]
members = [
    "neo-contract",
    "neo-contract-proc-macros",
    "neo-compiler",
    "examples/dao",
]

resolver = "2"

[profile.release]
lto = true
opt-level = 's' # Optimize for size
codegen-units = 1
panic = 'abort'

# Special configuration for WASM compilation
[profile.release.package.neo-contract]
opt-level = 'z' # Optimize aggressively for size
