//! Main Neo compiler implementation.
//!
//! This module provides the main compiler implementation for converting
//! WebAssembly to Neo VM bytecode.

use crate::converter::WasmConverter;
use crate::error::Error;
use crate::manifest::{
    ContractAbi, ContractEventDefinition, ContractMethodDefinition, ContractParameterDefinition, Manifest,
};
use crate::nef::NefFile;
use crate::script::Script;
use crate::wasm::WasmModule;
use std::fs;
use std::path::{Path, PathBuf};

/// Options for compiling WebAssembly modules to Neo VM scripts
#[derive(Debug, Clone)]
pub struct CompilerOptions {
    /// Whether to optimize the generated bytecode (default: true)
    pub optimize: bool,
    
    /// Path to a JSON template for generating the manifest
    pub manifest_template: Option<PathBuf>,
    
    /// Key-value pairs to override in the manifest
    pub manifest_overrides: Option<Vec<ManifestOverride>>,
    
    /// Directory to output the compiled files
    pub output_dir: Option<PathBuf>,
    
    /// Name of the contract (defaults to WASM file name)
    pub contract_name: Option<String>,
    
    /// Whether to include debug information (default: false)
    pub debug: bool,
}

impl Default for CompilerOptions {
    fn default() -> Self {
        Self {
            optimize: true,
            manifest_template: None,
            manifest_overrides: None,
            output_dir: None,
            contract_name: None,
            debug: false,
        }
    }
}

/// Key-value override for contract manifest fields
#[derive(Debug, Clone)]
pub struct ManifestOverride {
    /// The key in the manifest to override
    pub key: String,
    
    /// The value to set for the key
    pub value: String,
}

/// Compiler for WebAssembly to Neo VM conversion
pub struct Compiler {
    options: CompilerOptions,
}

impl Default for Compiler {
    fn default() -> Self {
        Self {
            options: Default::default(),
        }
    }
}

impl Compiler {
    /// Creates a new compiler with default options.
    pub fn new() -> Self { Self { options: CompilerOptions::default() } }

    /// Creates a new compiler with the specified options.
    pub fn with_options(options: CompilerOptions) -> Self { Self { options } }

    /// Get a reference to the compiler options.
    pub fn get_options(&self) -> &CompilerOptions { &self.options }

    /// Sets the debug mode.
    pub fn with_debug(mut self, debug: bool) -> Self {
        self.options.debug = debug;
        self
    }

    /// Sets the optimization level.
    pub fn with_optimize(mut self, optimize: bool) -> Self {
        self.options.optimize = optimize;
        self
    }

    /// Sets the manifest template path.
    pub fn with_manifest_template<P: AsRef<Path>>(mut self, template_path: P) -> Self {
        self.options.manifest_template = Some(template_path.as_ref().to_path_buf());
        self
    }

    /// Sets the contract name.
    pub fn with_name(mut self, name: impl Into<String>) -> Self {
        self.options.contract_name = Some(name.into());
        self
    }

    /// Compiles a WebAssembly file to a Neo contract.
    ///
    /// # Arguments
    ///
    /// * `wasm_path` - Path to the WebAssembly file
    /// * `output_dir` - Output directory for the compiled files
    /// * `name` - Name of the contract
    ///
    /// # Returns
    ///
    /// * `Result<(), Error>` - Result of the compilation
    pub fn compile<P: AsRef<Path>>(&self, wasm_path: P, output_dir: P, name: &str) -> Result<(), Error> {
        // Read the WebAssembly module
        let wasm_path = wasm_path.as_ref();
        let wasm_data = fs::read(&wasm_path).map_err(|e| Error::Io(e.to_string()))?;
        let module = WasmModule::parse(&wasm_data)?;

        if self.options.debug {
            println!(
                "Loaded WebAssembly module: {} functions, {} exports",
                module.functions().len(),
                module.exports().len()
            );
        }

        // Convert WebAssembly to Neo script
        let converter = WasmConverter::new();
        let script_bytes = converter.convert_to_script(&module, self.options.optimize)?;
        let script = Script::from_bytes(&script_bytes);

        if self.options.debug {
            println!("Generated Neo script: {} bytes", script.bytes().len());
        }

        // Create the NEF file
        let mut nef = NefFile::with_script(script.bytes().to_vec());
        nef.finalize()?;

        // Generate the manifest
        let manifest = self.generate_manifest(name, &module)?;

        // Create the output directory if it doesn't exist
        fs::create_dir_all(&output_dir).map_err(|e| Error::Io(e.to_string()))?;

        // Save the NEF file and manifest
        let base_name = name.to_string();
        let nef_path = Path::new(&output_dir.as_ref()).join(format!("{}.nef", base_name));
        let manifest_path = Path::new(&output_dir.as_ref()).join(format!("{}.manifest.json", base_name));

        nef.save_to(&nef_path)?;
        manifest.save_to_file(&manifest_path)?;

        if self.options.debug {
            println!("Saved NEF file: {}", nef_path.display());
            println!("Saved manifest: {}", manifest_path.display());
        }

        Ok(())
    }

    /// Generates a manifest for the contract.
    pub fn generate_manifest(&self, name: &str, module: &WasmModule) -> Result<Manifest, Error> {
        // Create a basic manifest
        let manifest = if let Some(template_path) = &self.options.manifest_template {
            // Load the template and update it with the contract information
            let abi = self.generate_abi(module)?;
            Manifest::from_template(template_path, name, abi)?
        } else {
            // Create a new manifest from scratch
            let mut manifest = Manifest::new(name);

            // Use registered contract information if available
            if let Some(contract_info) = self.get_contract_descriptor() {
                manifest.set_author(&contract_info.author)?;
                manifest.set_email(&contract_info.email)?;
                manifest.set_description(&contract_info.description)?;
                manifest.set_version(&contract_info.version)?;
                
                // Set dynamic invoke feature if needed
                if contract_info.dynamic_invoke {
                    manifest.set_feature("dynamicInvoke", true)?;
                }
            }

            // Get registered methods and events
            let registered_methods = self.get_registered_methods();
            let registered_events = self.get_registered_events();
            let registered_standards = self.get_registered_standards();
            
            // Add the ABI methods and events
            let mut abi = self.generate_abi(module)?;
            
            // Enhance ABI with explicitly registered methods
            for registered_method in registered_methods {
                // Check if this method already exists in the ABI
                if !abi.methods.iter().any(|m| m.name == registered_method.name) {
                    // Validate method parameters
                    // Check for parameter name uniqueness
                    let mut param_names = std::collections::HashSet::new();
                    for name in &registered_method.param_names {
                        if !param_names.insert(name) {
                            return Err(Error::InvalidMethodDefinition(format!("Method '{}' has duplicate parameter name: '{}'", registered_method.name, name)));
                        }
                    }
                    
                    // Validate method parameters - convert and check types
                    let mut parameters = Vec::new();
                    for (name, type_str) in registered_method.param_names.iter()
                        .zip(registered_method.param_types.iter()) {
                        
                        // Verify the Rust type can be mapped to a valid Neo type
                        let neo_type = self.rust_type_to_neo_type(type_str);
                        
                        // Validate that the Neo type is valid for a method parameter
                        if !self.is_valid_neo_method_parameter_type(&neo_type, name) {
                            return Err(Error::InvalidMethodDefinition(format!("Method '{}' parameter '{}' has invalid Neo N3 type: '{}'", registered_method.name, name, neo_type)));
                        }
                        
                        parameters.push(ContractParameterDefinition::new(
                            name.clone().to_string(), 
                            neo_type.to_string()
                        ));
                    }
                    
                    // Validate return type
                    let return_type = self.rust_type_to_neo_type(&registered_method.return_type);
                    if !self.is_valid_neo_method_parameter_type(&return_type, &registered_method.name) {
                        return Err(Error::InvalidMethodDefinition(format!("Method '{}' has invalid Neo N3 return type: '{}'", registered_method.name, return_type)));
                    }
                    
                    // Add method to ABI
                    abi.methods.push(ContractMethodDefinition::new(
                        registered_method.name.clone(),
                        parameters,
                        return_type.to_string(),
                        registered_method.safe,
                    ));
                    
                    log::info!("Added method to manifest: {} (safe: {})", registered_method.name, registered_method.safe);
                } else {
                    // Update existing method, particularly its "safe" status
                    for method in &mut abi.methods {
                        if method.name == registered_method.name {
                            method.safe = registered_method.safe;
                            log::info!("Updated method '{}' safe status to: {}", method.name, method.safe);
                            break;
                        }
                    }
                }
            }
            
            // Enhance ABI with explicitly registered events
            for registered_event in registered_events {
                // Check if this event already exists in the ABI
                if !abi.events.iter().any(|e| e.name == registered_event.name) {
                    // Add event with parameters
                    let mut params = Vec::new();
                    for (i, (name, type_str)) in registered_event.param_names.iter()
                        .zip(registered_event.param_types.iter())
                        .enumerate() {
                        
                        // Verify the Rust type can be mapped to a valid Neo type
                        let neo_type = self.rust_type_to_neo_type(type_str);
                        
                        // Neo N3 supports these parameter types:
                        if !self.is_valid_neo_event_parameter_type(&neo_type, name) {
                            return Err(Error::InvalidEventDefinition(format!("Event '{}' parameter '{}' has invalid Neo N3 type: '{}'", registered_event.name, name, neo_type)));
                        }
                        
                        let mut param = ContractParameterDefinition::new(
                            name.clone(), 
                            neo_type.to_string()
                        );
                        
                        // Set indexed if needed
                        let is_indexed = registered_event.indexed_params.contains(&i);
                        param.indexed = is_indexed;
                        
                        params.push(param);
                    }
                    
                    // Add event to ABI
                    abi.events.push(ContractEventDefinition::new(
                        registered_event.name.clone(),
                        params,
                    ));
                    
                    log::info!("Added event to manifest: {}", registered_event.name);
                }
            }
            
            manifest = manifest.with_abi(abi);
            
            // Add supported standards if any were registered
            for standard in registered_standards {
                manifest.add_supported_standard(&standard)?;
            }

            // Set features
            let uses_storage = self.detect_storage_usage(module)?;
            manifest.set_feature("storage", uses_storage)?;
            
            // Add custom permissions as needed for Neo N3
            manifest.add_permission("*", "Default")?;

            manifest
        };

        manifest.validate()?;
        Ok(manifest)
    }

    /// Generates the ABI for the contract from the WebAssembly module.
    fn generate_abi(&self, module: &WasmModule) -> Result<ContractAbi, Error> {
        let mut methods = Vec::new();
        let mut events = Vec::new();

        // Find exported functions that should be exposed as methods
        for export in module.exports() {
            if export.kind != "function" {
                continue;
            }

            // Skip internal functions (those starting with underscore)
            if export.name.starts_with('_') || export.name == "deploy" {
                continue;
            }

            // Get the function signature
            let function = module
                .get_function_by_index(export.index as usize)
                .ok_or_else(|| Error::general(format!("Function index {} not found", export.index)))?;

            // Build parameter list
            let mut parameters = Vec::new();
            for (i, param_type) in function.params.iter().enumerate() {
                let param_name = format!("p{}", i);
                let neo_type = self.rust_type_to_neo_type(param_type);
                parameters.push(ContractParameterDefinition::new(param_name, neo_type));
            }

            // Determine return type
            let return_type = if function.returns.is_empty() {
                "Void".to_string()
            } else if function.returns.len() == 1 {
                self.rust_type_to_neo_type(&function.returns[0])
            } else {
                return Err(Error::general("Multiple return values not supported"));
            };

            // Create the method definition
            let method = ContractMethodDefinition::new(
                export.name.clone(),
                parameters,
                return_type,
                self.is_safe_method(&export.name),
            );

            methods.push(method);
        }

        // Detect events by analyzing imports for Runtime.notify calls
        // In Neo N3, events are properly emitted using the Runtime::notify method
        // The pattern is:
        // 1. Use ByteString::from() for event name
        // 2. Create an Array<Any> for parameters
        // 3. Convert parameters with Any::from()
        // 4. Use Runtime::notify(event_name, event_params)
        for import in module.imports() {
            // Look for Runtime module imports that represent event notifications
            if (import.module == "runtime" || import.module == "neo_runtime") && import.field == "notify" {
                // Found Runtime.notify import - this is used for event emission in Neo N3
                // Look for functions that create ByteString event names and call notify
                for func in module.functions() {
                    if let Some(name) = &func.name {
                        if name.starts_with("emit_") || name.contains("_event") {
                            // This is an event emitter function following Neo N3 patterns

                            // Extract the event name - typically it follows the emit_ prefix
                            // or is contained in a string literal in the function body
                            let event_name = if name.starts_with("emit_") {
                                name.trim_start_matches("emit_").to_string()
                            } else {
                                // Extract from function name
                                name.split('_')
                                    .find(|s| s == &"event")
                                    .map(|_| name.replace("_event", ""))
                                    .unwrap_or_else(|| name.to_string())
                            };

                            // Build parameter list based on function parameters
                            // In Neo N3, these parameters will be converted to Any type
                            let mut parameters = Vec::new();
                            for (i, param_type) in func.params.iter().enumerate() {
                                let param_name = format!("p{}", i);
                                let neo_type = self.rust_type_to_neo_type(param_type);
                                parameters.push(ContractParameterDefinition::new(param_name, neo_type));
                            }

                            events.push(ContractEventDefinition::new(
                                // Convert to CamelCase for Neo N3 convention
                                event_name
                                    .split('_')
                                    .map(|s| {
                                        let mut c = s.chars();
                                        match c.next() {
                                            None => String::new(),
                                            Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                                        }
                                    })
                                    .collect::<String>(),
                                parameters,
                            ));
                        }
                    }
                }
            }
        }

        // If we couldn't detect events, look for typical naming patterns in the code
        if events.is_empty() {
            // Look for potential event emitter functions in the module
            for func in module.functions() {
                if let Some(name) = &func.name {
                    if name.starts_with("emit_") || name.ends_with("_event") {
                        let event_name = if name.starts_with("emit_") {
                            name.trim_start_matches("emit_").to_string()
                        } else {
                            name.trim_end_matches("_event").to_string()
                        };

                        // Use CamelCase for the event name
                        let event_name = event_name
                            .split('_')
                            .map(|s| {
                                let mut c = s.chars();
                                match c.next() {
                                    None => String::new(),
                                    Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                                }
                            })
                            .collect::<String>();

                        // Build parameter list
                        let mut parameters = Vec::new();
                        for (i, param_type) in func.params.iter().enumerate() {
                            let param_name = format!("p{}", i);
                            let neo_type = self.rust_type_to_neo_type(param_type);
                            parameters.push(ContractParameterDefinition::new(param_name, neo_type));
                        }

                        events.push(ContractEventDefinition::new(event_name, parameters));
                    }
                }
            }
        }

        // Before returning, create and return the ContractAbi
        let mut abi = ContractAbi::new();
        
        // Add all methods to the ABI
        for method in methods {
            abi.add_method(method);
        }
        
        // Add all events to the ABI
        for event in events {
            abi.add_event(event);
        }
        
        Ok(abi)
    }

    /// Converts a WebAssembly type to a Neo type.
    fn rust_type_to_neo_type(&self, wasm_type: &str) -> String {
        // Map WebAssembly types to Neo types
        let neo_type = match wasm_type {
            "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "Int256" => "Integer",
            "bool" => "Boolean",
            "String" | "ByteString" => "String",
            "H160" | "Address" => "Hash160",
            "H256" => "Hash256",
            "Array" => "Array",
            "Map" => "Map",
            _ => "Any",
        };
        
        neo_type.to_string()
    }

    /// Determines if a method is safe (read-only).
    ///
    /// In Neo N3, safe methods are read-only and don't modify blockchain state.
    /// They are marked with #[safe] attribute in the contract and represented
    /// with "safe": true in the manifest.
    pub fn is_safe_method(&self, name: &str) -> bool {
        // First check if method was explicitly registered with #[safe] attribute
        let registered_methods = self.get_registered_methods();
        for method in registered_methods {
            if method.name == name {
                return method.safe;
            }
        }

        // If not explicitly registered, apply heuristics for common safe methods
        let safe_prefixes = ["get", "is", "has", "find", "total", "balance", "symbol", "name", "decimals", "version", "count"];
        for prefix in safe_prefixes.iter() {
            if name.starts_with(prefix) && !name.contains("update") && !name.contains("set") && !name.contains("delete") {
                return true;
            }
        }

        // Special case for common NEP-17 and NEP-11 read methods
        match name {
            "totalSupply" | "balanceOf" | "decimals" | "symbol" | "tokensOf" |
            "ownerOf" | "properties" | "tokens" | "tokenURI" => true,
            _ => false,
        }
    }

    /// Detects if the contract uses storage.
    fn detect_storage_usage(&self, module: &WasmModule) -> Result<bool, Error> {
        // Check for storage-related imports or exports
        for import in &module.imports {
            if import.module.contains("storage") || import.field.contains("storage") {
                return Ok(true);
            }
        }

        // Look for any globally imported storage functions
        for function in &module.functions {
            if function.name.as_ref().map_or(false, |name| name.contains("storage")) {
                return Ok(true);
            }
        }

        Ok(false)
    }

    /// Validates if a Neo type is valid for event parameters
    fn is_valid_neo_event_parameter_type(&self, neo_type: &str, _param_name: &str) -> bool {
        matches!(
            neo_type,
            "String" | "Integer" | "Boolean" | "Hash160" | "Hash256" | "ByteArray" | "PublicKey" | "Signature" | "Array" | "Map" | "Any"
        )
    }

    /// Validates if a Neo type is valid for method parameters and return types
    fn is_valid_neo_method_parameter_type(&self, neo_type: &str, _param_name: &str) -> bool {
        matches!(
            neo_type,
            "Void" | "String" | "Integer" | "Boolean" | "Hash160" | "Hash256" | "ByteArray" | "PublicKey" | "Signature" | "Array" | "Map" | "Any"
        )
    }

    // Replacement for neo_contract::manifest::get_contract_descriptor
    fn get_contract_descriptor(&self) -> Option<ContractDescriptor> {
        // This would typically come from neo_contract runtime, but we'll use a dummy implementation
        None
    }

    // Replacement for neo_contract::manifest::get_registered_methods
    fn get_registered_methods(&self) -> Vec<RegisteredMethod> {
        Vec::new()
    }

    // Replacement for neo_contract::manifest::get_registered_events
    fn get_registered_events(&self) -> Vec<RegisteredEvent> {
        Vec::new()
    }

    // Replacement for neo_contract::manifest::get_registered_standards
    fn get_registered_standards(&self) -> Vec<String> {
        Vec::new()
    }
}

/// Descriptor for contract information
#[derive(Debug, Clone, Default)]
pub struct ContractDescriptor {
    /// Author of the contract
    pub author: String,
    /// Email of the author
    pub email: String,
    /// Description of the contract
    pub description: String,
    /// Version of the contract
    pub version: String,
    /// Whether the contract can perform dynamic invokes
    pub dynamic_invoke: bool,
}

/// Information about a registered method
#[derive(Debug, Clone)]
pub struct RegisteredMethod {
    /// Name of the method
    pub name: String,
    /// Parameter names
    pub param_names: Vec<String>,
    /// Parameter types
    pub param_types: Vec<String>,
    /// Return type
    pub return_type: String,
    /// Whether the method is safe (read-only)
    pub safe: bool,
}

/// Information about a registered event
#[derive(Debug, Clone)]
pub struct RegisteredEvent {
    /// Name of the event
    pub name: String,
    /// Parameter names
    pub param_names: Vec<String>,
    /// Parameter types
    pub param_types: Vec<String>,
    /// Indices of indexed parameters
    pub indexed_params: Vec<usize>,
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_compiler_basics() {
        // This is just a template for a test
        // We'd need a sample WebAssembly file to test with

        // For now, just check that we can create a compiler
        let compiler = Compiler::new();
        assert!(!compiler.options.debug);
        assert!(compiler.options.optimize);

        // Test the builder pattern
        let compiler = Compiler::new().with_debug(true).with_optimize(false);

        assert!(compiler.options.debug);
        assert!(!compiler.options.optimize);
    }
}
