// Copyright @ 2024 - present, R3E Network
// All Rights Reserved.

#![no_std]
#![no_main]

use neo_contract as neo;

use neo::{contract::*, types::*};

pub struct DemoNep11Token;

// #[neo::structs] will convert a rust struct into a neo contract struct
// NOTE: Cannot use any field directly, must use methods generated by #[neo::structs]
#[neo::structs]
pub struct DemoNep11TokenState {
    // #[get(pub)] will generate a method `pub fn name()` to get it
    #[get(pub)]
    name: ByteString,

    // #[get(pub)] will generate a method `pub fn owner()` to get it
    // #[set] will generate a method `fn set_owner` to set it, and use #[set(pub)] if want to be public)
    #[get(pub)]
    #[set]
    owner: H160,
}

impl Nep11TokenState for DemoNep11TokenState {
    /// NOTE: must be #[inline(always)]
    #[inline(always)]
    fn token_name(&self) -> ByteString {
        self.name() // This is a method generated by #[neo::structs]
    }

    /// NOTE: must be #[inline(always)]
    #[inline(always)]
    fn token_owner(&self) -> H160 {
        self.owner() // This is a method generated by #[neo::structs]
    }

    /// NOTE: must be #[inline(always)]
    #[inline(always)]
    fn set_token_owner(&mut self, owner: H160) {
        self.set_owner(owner); // This is a method generated by #[neo::structs]
    }
}

#[neo::contract]
impl Nep11Token<DemoNep11TokenState> for DemoNep11Token {
    fn symbol() -> ByteString {
        ByteString::empty()
    }

    fn decimals() -> u32 {
        8
    }
}
