#![no_std]
#![cfg_attr(target_arch = "wasm32", feature(core_intrinsics, lang_items))]
#![feature(alloc_error_handler)]

extern crate alloc;

use alloc::string::ToString;
use neo_contract::prelude::*;

#[contract]
mod event_demo_contract {
    use super::*;

    // Define events following ink! style syntax
    pub struct Transfer {
        #[index]
        from: Option<H160>,
        #[index]
        to: Option<H160>,
        amount: Int256,
    }

    pub struct Mint {
        #[index]
        to: H160,
        amount: Int256,
    }

    pub struct Burn {
        #[index]
        from: H160,
        amount: Int256,
    }

    const OWNER_KEY: &[u8] = b"owner";
    const BALANCES_PREFIX: &[u8] = b"balances";
    const TOTAL_SUPPLY_KEY: &[u8] = b"total_supply";

    #[storage]
    struct EventDemoContract {
        owner: H160,
        balances: Map<H160, Int256>,
        total_supply: Int256,
    }

    impl EventDemoContract {
        #[constructor]
        pub fn new() -> Self {
            Self {
                owner: H160::zero(),
                balances: Map::new(),
                total_supply: Int256::zero(),
            }
        }

        // Read-only methods marked with #[safe]
        #[safe]
        pub fn get_owner(&self) -> H160 { self.owner.clone() }

        #[method]
        pub fn set_owner(&mut self, owner: H160) -> bool {
            // Check if the caller is the current owner
            let current_owner = Runtime::check_witness();
            if current_owner.is_none() || current_owner.unwrap() != self.owner {
                return false;
            }

            self.owner = owner;
            true
        }

        #[safe]
        pub fn get_balance(&self, address: H160) -> Int256 {
            self.balances.get(&address).unwrap_or_else(|| Int256::zero())
        }

        // Internal method to set balance
        #[method]
        fn set_balance(&mut self, address: H160, balance: Int256) { self.balances.insert(address, balance); }

        #[safe]
        pub fn get_total_supply(&self) -> Int256 { self.total_supply.clone() }

        // Internal method to set total supply
        #[method]
        fn set_total_supply(&mut self, amount: Int256) { self.total_supply = amount; }

        // Emit the Transfer event following Neo N3 standards
        #[safe]
        fn emit_transfer(&self, from: Option<H160>, to: Option<H160>, amount: Int256) {
            // Create event name as ByteString
            let event_name = ByteString::from("Transfer");

            // Create an Array to hold parameters
            let mut event_data = Array::<Any>::new();

            // Add parameters as Any values
            match from {
                Some(addr) => event_data.push(Any::from(addr)),
                None => event_data.push(Any::new()),
            }

            match to {
                Some(addr) => event_data.push(Any::from(addr)),
                None => event_data.push(Any::new()),
            }

            event_data.push(Any::from(amount));

            // Emit the event
            Runtime::notify(&event_name, &event_data);
        }

        // Emit the Mint event following Neo N3 standards
        #[safe]
        fn emit_mint(&self, to: H160, amount: Int256) {
            // Create event name as ByteString
            let event_name = ByteString::from("Mint");

            // Create an Array to hold parameters
            let mut event_data = Array::<Any>::new();

            // Add parameters as Any values
            event_data.push(Any::from(to));
            event_data.push(Any::from(amount));

            // Emit the event
            Runtime::notify(&event_name, &event_data);
        }

        // Emit the Burn event following Neo N3 standards
        #[safe]
        fn emit_burn(&self, from: H160, amount: Int256) {
            // Create event name as ByteString
            let event_name = ByteString::from("Burn");

            // Create an Array to hold parameters
            let mut event_data = Array::<Any>::new();

            // Add parameters as Any values
            event_data.push(Any::from(from));
            event_data.push(Any::from(amount));

            // Emit the event
            Runtime::notify(&event_name, &event_data);
        }
    }

    // The manifest is auto-generated by the #[contract] macro
    // Events are registered through the trait definitions

    #[method]
    pub fn deploy() -> bool {
        let mut contract = EventDemoContract::new();

        // Get the calling script hash as the contract owner
        let tx = Runtime::calling_script_hash();
        contract.owner = tx;

        // Emit a Deploy event using Neo N3 standards
        let event_name = ByteString::from("Deploy");
        let mut event_data = Array::<Any>::new();
        event_data.push(Any::from(tx));
        Runtime::notify(&event_name, &event_data);

        true
    }

    #[method]
    pub fn transfer(from: H160, to: H160, amount: Int256) -> bool {
        let mut contract = EventDemoContract::new();

        // Verify that the sender has authorized this operation
        if !Runtime::check_witness(&from) {
            return false;
        }

        // Check amount validity
        if amount <= Int256::zero() {
            return false;
        }

        // Get current balances
        let from_balance = contract.get_balance(from.clone());

        // Check if the sender has enough balance
        if from_balance < amount {
            return false;
        }

        // Update balances
        let new_from_balance = from_balance - amount.clone();
        contract.set_balance(from.clone(), new_from_balance);

        let to_balance = contract.get_balance(to.clone());
        let new_to_balance = to_balance + amount.clone();
        contract.set_balance(to.clone(), new_to_balance);

        // Emit transfer event using the helper function
        contract.emit_transfer(Some(from), Some(to), amount);

        true
    }

    #[method]
    pub fn mint(to: H160, amount: Int256) -> bool {
        let mut contract = EventDemoContract::new();

        // Only owner can mint
        let owner = contract.get_owner();
        if !Runtime::check_witness(&owner) {
            return false;
        }

        // Check amount validity
        if amount <= Int256::zero() {
            return false;
        }

        // Update balance and total supply
        let balance = contract.get_balance(to.clone());
        let new_balance = balance + amount.clone();
        contract.set_balance(to.clone(), new_balance);

        let total_supply = contract.get_total_supply();
        let new_total_supply = total_supply + amount.clone();
        contract.set_total_supply(new_total_supply);

        // Emit events
        contract.emit_transfer(None, Some(to.clone()), amount.clone());

        // Emit Mint event using the helper method
        contract.emit_mint(to, amount);

        true
    }

    #[method]
    pub fn burn(from: H160, amount: Int256) -> bool {
        let mut contract = EventDemoContract::new();

        // Verify that the sender has authorized this operation
        if !Runtime::check_witness(&from) {
            return false;
        }

        // Check amount validity
        if amount <= Int256::zero() {
            return false;
        }

        // Get current balance
        let balance = contract.get_balance(from.clone());

        // Check if the sender has enough balance
        if balance < amount {
            return false;
        }

        // Update balance and total supply
        let new_balance = balance - amount.clone();
        contract.set_balance(from.clone(), new_balance);

        let total_supply = contract.get_total_supply();
        let new_total_supply = total_supply - amount.clone();
        contract.set_total_supply(new_total_supply);

        // Emit events
        contract.emit_transfer(Some(from.clone()), None, amount.clone());

        // Emit Burn event using the helper method
        contract.emit_burn(from, amount);

        true
    }

    #[safe]
    pub fn total_supply() -> Int256 {
        let contract = EventDemoContract::new();
        contract.get_total_supply()
    }

    #[safe]
    pub fn balance_of(address: H160) -> Int256 {
        let contract = EventDemoContract::new();
        contract.get_balance(address)
    }
}
