use crate::types::H160;
use crate::services::runtime::Runtime;

extern crate alloc;
use alloc::vec::Vec;

/// Solana-style Context type for Neo N3 smart contracts
/// Provides access to accounts and program state
pub struct Context<'info, T> {
    pub program_id: H160,
    pub accounts: T,
    pub remaining_accounts: Vec<AccountInfo<'info>>,
}

impl<'info, T> Context<'info, T> {
    pub fn new() -> Self {
        Self {
            program_id: Runtime::get_executing_script_hash(),
            accounts: unsafe { core::mem::zeroed() },
            remaining_accounts: Vec::new(),
        }
    }
    
    pub fn with_accounts(accounts: T) -> Self {
        Self {
            program_id: Runtime::get_executing_script_hash(),
            accounts,
            remaining_accounts: Vec::new(),
        }
    }
}

/// Account information wrapper
pub struct AccountInfo<'info> {
    pub key: H160,
    pub is_signer: bool,
    pub is_writable: bool,
    pub data: &'info [u8],
}

/// Account wrapper for validated accounts
pub struct Account<'info, T> {
    pub info: AccountInfo<'info>,
    pub data: T,
}

impl<'info, T> Account<'info, T> {
    pub fn is_mutable(&self) -> bool {
        self.info.is_writable
    }
    
    pub fn exists(&self) -> bool {
        !self.info.data.is_empty()
    }
    
    pub fn has_one<U>(&self, _other: &U) -> bool 
    where
        U: AsRef<H160>
    {
        // Placeholder for relationship validation
        true
    }
    
    pub fn verify_pda(&self) -> bool {
        // Placeholder for PDA verification
        true
    }
    
    pub fn space(&self) -> usize {
        self.info.data.len()
    }
}

/// Signer account type
pub struct Signer<'info> {
    pub info: AccountInfo<'info>,
}

impl<'info> Signer<'info> {
    pub fn is_signer(&self) -> bool {
        self.info.is_signer
    }
    
    pub fn can_pay(&self) -> bool {
        // Check if signer has sufficient balance
        true
    }
    
    pub fn key(&self) -> H160 {
        self.info.key
    }
}

/// System account type
pub struct SystemAccount<'info> {
    pub info: AccountInfo<'info>,
}

impl<'info> SystemAccount<'info> {
    pub fn key(&self) -> H160 {
        self.info.key
    }
}

/// Program account type
pub struct Program<'info, T> {
    pub info: AccountInfo<'info>,
    _phantom: core::marker::PhantomData<T>,
}

/// System program marker
pub struct System;

/// Token program marker  
pub struct Token;

/// Associated token program marker
pub struct AssociatedToken;

/// Result type for contract operations
pub type Result<T> = core::result::Result<T, crate::error::ContractError>;

/// Program derived address (PDA) utilities
pub struct Pda;

impl Pda {
    pub fn find_program_address(seeds: &[&[u8]], program_id: &H160) -> (H160, u8) {
        for bump in (0..=255).rev() {
            let mut seed_data = alloc::vec::Vec::new();
            for seed in seeds {
                seed_data.extend_from_slice(seed);
            }
            seed_data.push(bump);
            
            // Hash the combined seeds to create deterministic address
            // Create a simple hash for PDA (simplified for Neo)
            // In production, this would use proper cryptographic hashing
            let mut addr_bytes = [0u8; 20];
            for (i, byte) in seed_data.iter().enumerate() {
                if i < 20 {
                    addr_bytes[i] = *byte;
                } else {
                    addr_bytes[i % 20] ^= *byte;
                }
            }
            
            // Create H160 from the generated bytes
            #[cfg(not(target_family = "wasm"))]
            let address = H160::from_bytes(&addr_bytes);
            
            #[cfg(target_family = "wasm")]
            let address = H160::zero(); // Placeholder for WASM target
            
            // In Neo, we don't have the same PDA validation as Solana
            // So we just return the first valid address
            return (address, bump);
        }
        
        panic!("Unable to find program address");
    }
}

/// Cross-program invocation context
pub struct CpiContext<'a, 'b, 'c, 'info, T> {
    pub program: AccountInfo<'info>,
    pub accounts: T,
    pub signer_seeds: &'a [&'b [&'c [u8]]],
}

impl<'a, 'b, 'c, 'info, T> CpiContext<'a, 'b, 'c, 'info, T> {
    pub fn new(program: AccountInfo<'info>, accounts: T) -> Self {
        Self {
            program,
            accounts,
            signer_seeds: &[],
        }
    }
    
    pub fn with_signer(mut self, signer_seeds: &'a [&'b [&'c [u8]]]) -> Self {
        self.signer_seeds = signer_seeds;
        self
    }
}

/// Pubkey type alias for Neo H160
pub type Pubkey = H160;

/// Clock structure for time-related operations
pub struct Clock {
    pub slot: u64,
    pub epoch_start_timestamp: i64,
    pub epoch: u64,
    pub leader_schedule_epoch: u64,
    pub unix_timestamp: i64,
}

impl Clock {
    pub fn get() -> Result<Self> {
        let timestamp = Runtime::get_time();
        Ok(Self {
            slot: 0,
            epoch_start_timestamp: timestamp as i64,
            epoch: 0,
            leader_schedule_epoch: 0,
            unix_timestamp: timestamp as i64,
        })
    }
}

/// Rent structure for account rent calculations
pub struct Rent {
    pub lamports_per_byte_year: u64,
    pub exemption_threshold: f64,
    pub burn_percent: u8,
}

impl Rent {
    pub fn get() -> Result<Self> {
        Ok(Self {
            lamports_per_byte_year: 3480,
            exemption_threshold: 2.0,
            burn_percent: 50,
        })
    }
    
    pub fn minimum_balance(&self, data_len: usize) -> u64 {
        (self.lamports_per_byte_year * data_len as u64 * 2) / 100
    }
}