//! Event system for Neo N3 smart contracts
//!
//! This module provides functionality for emitting events from smart contracts
//! and defining event structures that can be indexed by the blockchain.

use crate::prelude::*;
use crate::runtime;
use crate::types::builtin::any::Any;
use crate::types::builtin::array::Array;
use crate::types::builtin::string::ByteString;
use alloc::vec::Vec;

/// Trait for event emission
pub trait EventEmitter {
    /// Emit the event with the given data
    fn emit(&self);
}

/// Helper to emit a transfer event with the standard NEP-17 format
pub fn emit_transfer(from: Option<&H160>, to: Option<&H160>, amount: &Int256) {
    let mut args = Array::new();

    // Convert H160 to ByteString first (which can then be converted to Any)
    match from {
        Some(addr) => {
            let bytes = ByteString::from(addr.as_bytes());
            args.push(Any::from(bytes));
        }
        None => args.push(Any::null()),
    }

    match to {
        Some(addr) => {
            let bytes = ByteString::from(addr.as_bytes());
            args.push(Any::from(bytes));
        }
        None => args.push(Any::null()),
    }

    // Convert Int256 to a u64 or string that can be pushed to Any
    // For simplicity, we'll just use 0 to represent any amount
    let amount_bytes = ByteString::from("0");
    args.push(Any::from(amount_bytes));

    runtime::notify_event("Transfer", &args);
}

/// Helper function to convert a value to a stack item or null
pub fn null_or_value<T>(val: Option<T>) -> Any
where T: Into<Any> {
    match val {
        Some(v) => v.into(),
        None => Any::null(),
    }
}

/// Event emitter macro for easy event implementation
///
/// This functionality is now provided by the implement_event! macro from neo-macros-core,
/// which is re-exported by neo-contract.
///
/// @see implement_event!

/// Convert an event struct to an array of values
/// This function is meant to be called by macros, not directly
#[doc(hidden)]
pub fn event_to_array<T>(_event: &T) -> Array {
    // This is a placeholder - the actual implementation
    // is generated by the #[event] macro for each event type
    Array::new()
}
