[package]
name = "neo-features-showcase"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
neo-contract = { path = "../../neo-contract" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[dependencies.wee_alloc]
version = "0.4"
